apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-g2vg
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0034-tenant/tkrw-pr712-0075-0034-app/devfile-sample-g2vg@sha256:44d1fee7147b13abb76f33bd14ffa4ff99ec486c24c5f255f7307ddadeaa3d36
        name: my-nodejs
        resources: {}
status: {}
